package tech.amcg.llf.domain.response.mapping;

public enum TubeLine {
    JUBILEE, METROPOLITAN, HAMMERSMITHANDCITY, NORTHERN, BAKERLOO, CENTRAL, CIRCLE, DISTRICT, VICTORIA, ELIZABETH, PICADILLY, DLR, WATERLOOANDCITY, UNKNOWN;
}
